version: "3.9"
services:
  catalog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: auction
    environment:
      - CATALOG_PORT=7001
    ports:
      - "7001:7001"

  validator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: bidding
    environment:
      - VALIDATOR_PORT=7002
    ports:
      - "7002:7002"

  history:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: history
    environment:
      - HISTORY_PORT=7003
    ports:
      - "7003:7003"

  updates:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: updates
    environment:
      - UPDATES_PORT=7004
    ports:
      - "7004:7004"

  notifier:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: notifier
    environment:
      - NOTIFIER_PORT=7005
    ports:
      - "7005:7005"

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: aggregator
    environment:
      - GATEWAY_PORT=7000
      - CATALOG_ADDR=catalog:7001
      - VALIDATOR_ADDR=validator:7002
      - HISTORY_ADDR=history:7003
      - UPDATES_ADDR=updates:7004
      - NOTIFIER_ADDR=notifier:7005
    ports:
      - "7000:7000"
    depends_on:
      - catalog
      - validator
      - history
      - updates
      - notifier
